antora:
  extensions:
  - '@antora/collector-extension'
  - '@antora/lunr-extension'
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: junit
  - require: '@springio/antora-extensions/root-attachments-extension'
site:
  title: JUnit User Guide
  url: https://docs.junit.org
  robots: allow
content:
  sources:
  - url: ../main
    branches: antora-migration
    start_path: documentation
asciidoc:
  attributes:
    page-pagination: ''
runtime:
  fetch: true
  log:
    failure_level: warn
urls:
  latest_version_segment: current
  latest_prerelease_version_segment: snapshot
  latest_version_segment_strategy: redirect:to
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
