name: Sanity Check ğŸ•Š
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'
permissions: {}
jobs:
  validate:
    name: Validate ğŸ“Š
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Checkstyle â˜‘ï¸
        uses: ./.github/actions/run-gradle
        with:
          encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: checkstyleMain
      - name: Spotless âœ¨
        uses: ./.github/actions/run-gradle
        with:
          encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: spotlessCheck
      - name: ArchUnit ğŸ›ï¸
        uses: ./.github/actions/run-gradle
        with:
          encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: archUnit
      - name: OSGi ğŸ§©
        uses: ./.github/actions/run-gradle
        with:
          encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: verifyOSGiTask
      - name: Rewrite âš™ï¸
        uses: ./.github/actions/run-gradle
        with:
          encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: rewriteDryRun -Dorg.gradle.jvmargs=-Xmx2G
